import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import eslintConfigPrettier from 'eslint-config-prettier/flat';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import eslintPluginBetterTailwindcss from 'eslint-plugin-better-tailwindcss';
import { importX } from 'eslint-plugin-import-x';
import reactCompiler from 'eslint-plugin-react-compiler';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import storybook from 'eslint-plugin-storybook';
import unicorn from 'eslint-plugin-unicorn';
import unusedImports from 'eslint-plugin-unused-imports';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig(
	{
		ignores: [
			'dist',
			'dev-dist',
			'.wrangler',
			'worker-configuration.d.ts',
			'.storybook',
			'storybook-static',
			'worker/lib/preview-scripts',
			// AudioWorklet processor — runs in worklet scope, not main thread
			'src/features/agent/lib/pcm-processor.js',
			'landing',
			// Auto-generated type declarations for auxiliary workers
			'auxiliary/*/worker-configuration.d.ts',
			// Vendored native plugin bundle (generated by scripts/vendor-vite-host.ts)
			'auxiliary/vite-host/vendor',
			// Fixture files are user project templates — they use Cloudflare conventions (Env, not Environment)
			'worker/fixtures/**/worker-env.d.ts',
			// Static public assets (vendored service worker, etc.)
			'public',
			// Generated Playwright reports
			'playwright-report',
		],
	},

	js.configs.recommended,

	tseslint.configs.recommended,
	{
		files: ['**/*.{ts,tsx}'],
		languageOptions: {
			ecmaVersion: 2022,
			globals: globals.browser,
			parserOptions: {
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
			},
		},

		rules: {
			'@typescript-eslint/no-floating-promises': 'error',
			'@typescript-eslint/consistent-type-assertions': ['error', { assertionStyle: 'never' }],
			'@typescript-eslint/no-unused-expressions': ['error', { allowTaggedTemplates: true }],
		},
	},

	unicorn.configs.recommended,

	reactHooks.configs.flat.recommended,
	reactRefresh.configs.vite,
	reactCompiler.configs.recommended,
	{
		// Template fixtures are shipped to users as source strings, not part of the
		// IDE's own React tree. vinext layouts idiomatically export both a
		// component and `metadata`, which the fast-refresh rule would otherwise flag.
		files: ['worker/fixtures/**/*.{ts,tsx}'],
		rules: {
			'react-refresh/only-export-components': 'off',
		},
	},
	{
		rules: {
			'no-restricted-syntax': [
				'error',
				{
					selector: "CallExpression[callee.property.name='forwardRef'], CallExpression[callee.name='forwardRef']",
					message: 'forwardRef is deprecated in React 19. Use ref as a prop instead.',
				},
			],
		},
	},

	importX.flatConfigs.recommended,
	{
		files: ['src/**/*.{ts,tsx}'],
		ignores: ['src/**/*.test.{ts,tsx}', 'src/**/*.stories.{ts,tsx}'],
		rules: {
			'no-restricted-imports': [
				'error',
				{
					patterns: [
						{
							group: ['@worker/**', '@server/**'],
							allowTypeImports: true,
							message: 'Browser code may import Worker route types, but not Worker runtime values.',
						},
					],
				},
			],
		},
	},
	{
		files: ['worker/**/*.{ts,tsx}', 'shared/**/*.{ts,tsx}'],
		rules: {
			'no-restricted-imports': [
				'error',
				{
					patterns: [{ group: ['@/**'], message: 'Worker and shared code must not depend on browser modules.' }],
				},
			],
		},
	},
	{
		settings: {
			'import-x/resolver-next': [
				createTypeScriptImportResolver({
					alwaysTryTypes: true,
					bun: true,
					project: import.meta.dirname,
				}),
			],
		},
		rules: {
			'import-x/order': [
				'error',
				{
					groups: ['builtin', 'external', 'internal', ['parent', 'sibling', 'index'], 'type'],
					'newlines-between': 'always',
					alphabetize: {
						order: 'asc',
						caseInsensitive: true,
					},
				},
			],
			'import-x/no-unresolved': [
				'error',
				{
					ignore: ['cloudflare:*', 'virtual:*', 'drizzle-orm/*', '@modelcontextprotocol/sdk/*'],
				},
			],
		},
	},

	{
		plugins: {
			'unused-imports': unusedImports,
		},
		rules: {
			'@typescript-eslint/no-unused-vars': 'off',
			'unused-imports/no-unused-imports': 'error',
			'unused-imports/no-unused-vars': [
				'warn',
				{
					vars: 'all',
					varsIgnorePattern: '^_',
					args: 'after-used',
					argsIgnorePattern: '^_',
				},
			],
		},
	},

	storybook.configs['flat/recommended'],
	{
		files: ['**/*.stories.{ts,tsx}'],
		rules: {
			// Meta/StoryObj types are only exported from @storybook/react, not @storybook/react-vite
			'storybook/no-renderer-packages': 'off',
		},
	},

	eslintConfigPrettier,

	{
		files: ['**/*.{ts,tsx}'],
		ignores: ['worker/fixtures/**'],
		plugins: {
			'better-tailwindcss': eslintPluginBetterTailwindcss,
		},
		rules: {
			...eslintPluginBetterTailwindcss.configs['recommended-warn'].rules,
			...eslintPluginBetterTailwindcss.configs['recommended-error'].rules,
			'better-tailwindcss/enforce-consistent-line-wrapping': [
				'error',
				{
					indent: 'tab',
					strictness: 'loose',
				},
			],
		},
		settings: {
			'better-tailwindcss': {
				entryPoint: 'src/index.css',
			},
		},
	},

	// Test files need type assertions to narrow unknown results from tool execute functions
	{
		files: ['**/*.test.{ts,tsx}', '**/test-helpers.ts'],
		rules: {
			'@typescript-eslint/consistent-type-assertions': 'off',
			'better-tailwindcss/no-unknown-classes': 'off',
		},
	},

	// FOUC-prevention script runs in the browser and uses build-time replacements
	{
		files: ['src/lib/fouc-prevention.js'],
		languageOptions: {
			globals: {
				...globals.browser,
				__DEFAULT_EDITOR_FONT__: 'readonly',
				__EDITOR_FONT_FAMILIES__: 'readonly',
			},
		},
		rules: {
			'no-empty': ['error', { allowEmptyCatch: true }],
		},
	},
);
