/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=auxiliary/email/wrangler.jsonc --include-runtime=false --env-interface=EmailWorkerEnvironment auxiliary/email/worker-configuration.d.ts` (hash: 7b33045994be5dbf39b1099da2ceaf50)
interface __BaseEnv_EmailWorkerEnvironment {
	EMAIL: SendEmail;
	EMAIL_QUEUE: Queue;
	EMAIL_HIGH_QUEUE: Queue;
	EMAIL_FROM: "Codemaxxing.ai <noreply@codemaxxing.ai>";
}
declare namespace CloudflareEmailWorker {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_EmailWorkerEnvironment {}
}
interface EmailWorkerEnvironment extends __BaseEnv_EmailWorkerEnvironment {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<CloudflareEmailWorker.Env, "EMAIL_FROM">> {}
}
